import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import { Background } from "./background";
import Navbar from "./Navbar";

type LayoutProps = {
  children: React.ReactNode;
};

export default function Layout({ children }: LayoutProps): JSX.Element {
  return (
    <>
      <Head>
        <title>PasteWin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        tabIndex={0}
        className="relative flex h-fit min-h-full w-full flex-col text-neutral-800 dark:bg-black/50 dark:text-indigo-50"
      >
        <Background></Background>
        <SessionProvider>
          {" "}
          <Navbar></Navbar>
          {children}
        </SessionProvider>
      </div>
    </>
  );
}
